### ISSUE TITLE
remove the dash from the package name

### ISSUE THREAD

**Issue by buhtz** [pyexcel/pyexcel-ezodf#8]
It is "unpythonic" to use dashes in package names. See this for details.
https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them#761531

**Comment by chfw** [comment]
I see your point. If I would have done from scratch, I would have taken your advice. However the name tries to assert it is a variant of ezodf from pyexcel. The actual module is ezodf when you see it code.

I knew it is odd. But the oddity comes from the maintenance history. So, I would like to respect it instead of trying to wipe it out.

By the way, would you be interested in the co-maintenanership?
